name: Docker Build and Publish

on:
  push:
    branches: [ "main" ]
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        id: meta
        run: |
          # Use tag from GitHub release or commit SHA for main branch
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT
          else
            SHA=$(git rev-parse --short HEAD)
            echo "VERSION=${SHA}" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/jellyhook-api:${{ steps.meta.outputs.VERSION }}
      
      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./workers
          file: ./workers/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/jellyhook-worker:${{ steps.meta.outputs.VERSION }}