name: Docker Build and Publish

on:
  push:
    branches: [main]
  release:
    types: [published]
  repository_dispatch:
    types: [release-published]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}

jobs:
  setup:
    name: Setup Build Environment
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.set_tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Extract SHA for release tag
        id: set_tag
        run: |
          SHA=$(git rev-parse --short HEAD)
          echo "tag=${SHA}" >> $GITHUB_OUTPUT

      - name: Get release tag from payload
        if: github.event_name == 'repository_dispatch'
        id: set_tag_dispatch
        run: |
          echo "tag=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT

      - name: Get tag from release
        if: github.event_name == 'release'
        id: set_tag_release
        run: |
          echo "tag=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

  build-api:
    needs: setup
    name: Build API Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/jellyhook-api:${{ needs.setup.outputs.release_tag }}

  build-worker:
    needs: setup
    name: Build Worker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Worker image
        uses: docker/build-push-action@v5
        with:
          context: ./workers
          file: ./workers/Dockerfile
          platforms: linux/amd64,linux/arm64
          provenance: false
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/jellyhook-worker:${{ needs.setup.outputs.release_tag }}
